upstream:
  default:
    - https://cloudflare-dns.com/dns-query
    - https://fi.doh.dns.snopyta.org/dns-query
    - https://doh.libredns.gr/dns-query
    - https://doh-ch.blahdns.com:4443/dns-query
customDNS:
  mapping:
    vmk-cicd-01: 10.10.2.2
    vmk-man-01: 10.10.2.3
    vmk-prod-02: 10.10.2.5
    vmk-ext-01: 10.10.2.6
    vmk-prod-01: 10.10.2.7
    vmk-srv-01: 10.10.2.8
    vmk-rpi-01: 10.10.2.9
    
    proxy-srv.int.mxard.cloud: 10.10.2.8
    git.int.mxard.cloud: 10.10.2.8
    idp.int.mxard.cloud: 10.10.2.8
    proxy.int.mxard.cloud: 10.10.2.8
    prometheus.int.mxard.cloud: 10.10.2.8
    grafana.int.mxard.cloud: 10.10.2.8
    loki.int.mxard.cloud: 10.10.2.8

    proxy-01.int.mxard.cloud: 10.10.2.7
    downloader.int.mxard.cloud: 10.10.2.7
    flared.int.mxard.cloud: 10.10.2.7
    rente.int.mxard.cloud: 10.10.2.7
    emby.int.mxard.cloud: 10.10.2.7
    series.int.mxard.cloud: 10.10.2.7
    movies.int.mxard.cloud: 10.10.2.7
    jaeckli.int.mxard.cloud: 10.10.2.7
    dashboard.int.mxard.cloud: 10.10.2.7
    rss.int.mxard.cloud: 10.10.2.7
    cloud.int.mxard.cloud: 10.10.2.7

    proxy-02.int.mxard.cloud: 10.10.2.5
    core.int.mxard.cloud: 10.10.2.5

    drone.int.mxard.cloud: 10.10.2.2
blocking:
  blackLists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://raw.githubusercontent.com/notracking/hosts-blocklists/master/adblock/adblock.txt
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious
  clientGroupsBlock:
    default:
      - ads
  blockType: zeroIp
caching:
  prefetching: true
prometheus:
  enable: true
  path: /metrics
port: 53
httpPort: 4000
bootstrapDns: 1.1.1.1
disableIPv6: true